level: [0, 83, 174, 276, 388, 512, 650, 801, 969, 1154] # how much xp is required to progress to each level

pointsdropped:
  monster: 5
  default: 3

skills:
  haste:
    cost: 20
    duration: 200 # in ticks
    amplifier: 3
  burst:
    cost: 40
    power: 5.0
    range: 40
    setfire: true
