name: CustomXp
version: 1.0
author: ChenChai
main: ai.chench.customxp.CustomXp

commands:
  soulpoints:
    description: view, set or add custom xp of yourself. Can only add or set integers.
    usage: /soulpoints [view | add | set] <number of sp>
    aliases: soul
  setsoulpoints:
    description: set or add soul points. Must be an integer.
    usage: /setsoulpoints [ add | set ] <number of sp> <player>
    permission: 4
  skill:
    description: Consumes soul points to use a skill!
    usage: /skill [haste]